### ISSUE TITLE
Linea del tiempo de la web 1.0 2.0 3.0

### ISSUE THREAD

**Issue by Vanessacruzortiz** [SistemasTecTlaxiaco/actividad-7-Vanessacruzortiz#1]
actividad 7
[Linea del tiempo de la web 1.0, 2.0, 3.0.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-Vanessacruzortiz/files/9816181/Linea.del.tiempo.de.la.web.1.0.2.0.3.0.pdf)

**Comment by Blanca-estela-valerio-rivero** [comment]
tiene 18.5%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
